In [2]:
import numpy as np

In [3]:
fitbit = np.loadtxt('data/fitbit_data.txt', dtype=str)

In [4]:
fitbit.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [5]:
dates = fitbit[:, 0]

In [6]:
dates

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [7]:
step_count = fitbit[:, 1]

In [8]:
step_count = step_count.astype(dtype='int64')

In [9]:
step_count.mean()

2935.9375

In [10]:
step_count.shape

(96,)

In [11]:
mood = fitbit[:, 2]

In [12]:
(mood == 'Happy').sum()

40

In [13]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [14]:
a[a < 6]

array([1, 2, 3, 4, 5])

In [15]:
s = np.array([1, 3, 2])

In [16]:
a[[1, 2]]

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
import numpy as np

print(np.sort(np.array(['Ram', 'Astha', 'Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [18]:
arr1 = np.array(['Ram', 'Astha', 'Brahat'])
arr2 = np.array(['Shyam', 'Kalyan', 'Naveen'])
arr1 > arr2

array([False, False, False])

In [19]:
import numpy as np

arr = 2 * np.arange(0, 2, 0.5)
if arr <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
if arr <= 6.0:
    print('correct')

In [ ]:
a = np.array([[16, 5], [81, 6], [33, 1]])

In [ ]:
print(a)

In [ ]:
x = np.transpose(a).reshape(2, 3)

In [ ]:
x.flatten()

In [ ]:
a = np.array([[34, 28, 55], [8, 56, 3], [77, 87, 19]])

In [ ]:
a.T

In [ ]:
print(a.transpose()[-2, -2])

In [ ]:
a = np.array([[10, 14, 32], [12, 3, 4]])

In [ ]:
mask

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
mask = (a % 2 == 0) & (a > 3)

In [21]:
mask

array([[False, False, False],
       [ True, False,  True],
       [False,  True, False]])

In [22]:
np.all(mask)

False

In [23]:
np.all([4, 6, 18])

True

In [24]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [25]:
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [26]:
arr = np.zeros([3,3])

In [27]:
arr[range(3),range(3)]  =2 

In [28]:
row_count=3
k=300

In [29]:
result = np.zeros([row_count,row_count])
# result[range(row_count),range(row_count)] = k


In [30]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [31]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
a = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
b = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])


In [33]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [60]:
a = np.arange(1,11).reshape(-1,10)

In [61]:
b = np.arange(12,22).reshape(10,-1)

In [87]:
np.matmul(3,a)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [77]:
a = np.array([[1,2,3]])
b = np.array([[3],[2],[1]])

In [80]:
np.dot(a,b)

array([[10]])

In [73]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
b = np.array([[3,3,3], [2,2,2], [1,1,1]])

In [76]:
np.matmul(a,b)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [34]:
# Maximum and minimum step count recorded
max(step_count), min(step_count)

(7422, 25)

In [35]:
# Average step count across all days
step_count.mean()

2935.9375

In [36]:
# Average step count for each mood category (e.g., Neutral, Sad, Happy)
step_count_neutral = np.round(step_count[fitbit[:,2]=='Neutral'].mean(),2)
step_count_sad = np.round(step_count[fitbit[:,2]=='Sad'].mean(),2)
step_count_happy = np.round(step_count[fitbit[:,2]=='Happy'].mean(),2)

In [37]:
# Days on which Maximum and Minimum step count were recorded
max_step_count_day = fitbit[:,1].astype(dtype='int').max()
max_day = fitbit[np.where(fitbit[:,1].astype(dtype='int') == max_step_count_day)][0][0]
min_step_count_day = fitbit[:,1].astype(dtype='int').min()
min_day = fitbit[np.where(fitbit[:,1].astype(dtype='int') == min_step_count_day)][0][0]

In [38]:
# Total calories burned across all days
total_cals = fitbit[:,3].astype(dtype='int').sum()

In [39]:
# Average hours of sleep per day
avg_sleep_hours = fitbit[:,-2].astype(dtype='int').mean()

In [40]:
avg_sleep_hours

5.21875

In [41]:
# Days that are categorized as "Active" vs. "Inactive"
active_days = np.count_nonzero(fitbit[:,-1] == 'Active')
inactive_days = np.count_nonzero(fitbit[:,-1] == 'Inactive')

In [42]:
inactive_days

54