In [123]:
import numpy as np

In [166]:
a = np.arange(9).reshape(3,3)

In [167]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
a.T.shape

(4, 3)

In [145]:
a[:,1].argsort()

array([0, 1, 2], dtype=int64)

In [158]:
a[1,2]

6

In [147]:
b = np.array([1,2,3,4,5,6,7])

In [159]:
b

array([1, 2, 3, 4, 5, 6, 7])

In [171]:
a[[0,1,2],[0,1,2,]]

array([0, 4, 8])