In [3]:
class MyClass:
    language = 'Python'
    version = '3.6'

    def display(self, name):
        print(f"Hello {name}, welcome to {self.language} {self.version} world!")

In [4]:
p = MyClass()

In [ ]:
p.__dict__

In [ ]:
MyClass.__dict__

In [ ]:
a = 'l'

In [ ]:
MyClass.display(p, 'laks')

In [ ]:
type(MyClass.display)

In [ ]:
hex(id(p))

In [ ]:
p.display

In [ ]:
type(p.display)

In [ ]:
type(MyClass.display)

In [ ]:
amount = 0
units = 150
count = 0

In [ ]:
charges

In [ ]:
if units >= 200:
    amount = 100 * 3.5 + 100 * 5 + (units - 200) * 8 + 150
elif units >= 100:
    amount = 100 * 3.5 + (units - 100) * 5 + 150
else:
    amount = units * 3.5 + 150

In [ ]:
amount

In [ ]:
class A:
    def one(self):
        return self.two()

    def two(self):
        return 'A'


class B(A):
    def two(self):
        return 'B'


obj = B()
print(obj.one())

In [ ]:
class A:
    def __init__(self, name, sound="Grrrr"):
        self.name = name
        self.sound = sound

    def make_noise(self):
        print("{} says, {}".format(self.name, self.sound))


class B(A):
    def __init__(self, name="Rachel"):
        super().__init__(name, "Meow!")

    def make_noise(self, sound="Grrrr!"):
        print("{} says, {}".format(self.name, sound))


pet_cat = B()
pet_cat.make_noise()

In [ ]:
class A:

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):
        return 1

    def __eq__(self, other):
        return self.x * self.y == other.x * other.y


obj1 = A(9, 8)
obj2 = A(8, 9)
print(obj1 == obj2)

In [ ]:
class Person:
    def __init__(self, name):
        self.name = name
        print(f'Person with {self} called')

    def say_hello2(self):
        print("hello2")

In [ ]:
p1 = Person('laks')

In [ ]:
p1.__dict__

In [ ]:
Person.__dict__

In [ ]:
p1.section = '9th'

In [ ]:
p1.__dict__

In [ ]:
s = lambda: self

In [ ]:
p1.say_hello = s

In [ ]:
p1.__dict__

In [ ]:
type(p1.say_hello)

In [ ]:
p1.say_hello()

In [ ]:
class Student:
    section: 'A'

In [ ]:
s1 = Student()

In [ ]:
from types import MethodType

In [ ]:
s1.say_hello = MethodType(lambda self: print('hello'), s1)

In [ ]:
s1.say_hello2 = lambda: {'hello2'}

In [ ]:
s1.say_hello = MethodType(s1.say_hello2, s1)

In [ ]:
s1.say_hello2()

In [ ]:
getattr(s1, 'say_hello')

In [ ]:
def say_hello(self):
    return f'{self.name} says hello'

In [ ]:
s1.name = 'laks'

In [ ]:
s1.say_hello = MethodType(say_hello, s1)

In [ ]:
getattr(s1, 'say_hello')()

In [ ]:
s1.say_hello()

In [ ]:
class A:
    def __init__(self):
        pass

    def marks(self):
        return "marks"

    def __add__(self, other):
        return "hello"

In [ ]:
class B:
    def __init__(self):
        pass

    def marks(self):
        return "marks"

    def __add__(self, other):
        return "world"

In [ ]:
p3 = A()
p4 = B()

In [ ]:
p3 + p4

In [ ]:
x = [1, 2, 3]
y = x

In [ ]:
y.append(4)

In [ ]:
y

In [ ]:
x

In [ ]:
isinstance(float, object)

In [ ]:
10 / 3

In [ ]:
10 // 3

In [ ]:
-8 // 3

In [ ]:
-8 / 3

In [ ]:
_ = 2

In [ ]:
_

In [ ]:
a = 10

In [ ]:
id(a)

In [ ]:
b = 10

In [ ]:
id(b)

In [ ]:
c = 10

In [ ]:
id(c)

In [ ]:
d = 5 + 5

In [ ]:
id(d)

In [ ]:
e = "10"

In [ ]:
id(e)

In [ ]:
id(a)

In [ ]:
a = 21

In [ ]:
del a

In [ ]:
del b, c, d, e

In [ ]:
5 + 6


In [ ]:
6 + 7


In [ ]:
_

In [ ]:
for i in 'Laks':
    print(i)

In [ ]:
*range(0, 10)

In [ ]:
print(*'101')

In [ ]:
it = iter("12")

In [ ]:
next(it)

In [ ]:
next(it)

In [ ]:
next(it)

In [ ]:
a = [1, 2, 3, 4, 5]

In [ ]:
a[-3:1:1]

In [ ]:
a[::1]

In [ ]:
a[-2:0:-1]

In [ ]:
[1, 2, 3] * 2

In [ ]:
a = [1, 2, 3]

In [ ]:
id(a)

In [ ]:
a[0] = 4

In [ ]:
id(a)

In [ ]:
2 in a

In [ ]:
a = (1, 2, 3) + (4,)

In [ ]:
a += (5,)

In [ ]:
a

In [ ]:
id(a)

In [ ]:
a = {"orange": 1, "apple": 2, "banana": 3}

In [ ]:
a['apple']

In [ ]:
id(a)

In [ ]:
a['apple'] = 4

In [ ]:
id(a)

In [ ]:
a.update({'apple': 5})

In [ ]:
for i, j in a.items():
    print(i, j)

In [ ]:
print(range(0, 10))

In [ ]:
type(a.get('ap', 'Not Found'))

In [ ]:
b = {1: 1, 2: 1}

In [ ]:
type(b)

In [ ]:
b.values()

In [ ]:
c = {1, 2, 2}

In [ ]:
c

In [ ]:
c.add(1)

In [ ]:
c.add((4, 1))

In [ ]:
c

In [ ]:
i = 1
for i in range(0, 1000, i * 100):
    print(i)

In [ ]:
i = 1
a = iter(range(0, 10, i * 2))

In [ ]:
print(a)

In [ ]:
print(*a)

In [ ]:
count = 0
n = 3
loop_exec = 0
for i in range(n + 1):
    j = 1
    for j in range(1, n + 1, j * 2):
        loop_exec += 1
print(loop_exec)

In [ ]:
n = 4
loop_exec = 0
for j in range(1, n + 1, j * 2):
    loop_exec += 1
print(loop_exec)

In [ ]:
print(*iter(range(1, 5, 6)))

In [ ]:
k = 1
for k in range(1, 15, 2 * k):
    print(k)

In [ ]:
k

In [ ]:
def func(N):
    i = 1
    s = 0
    for i in range(1, N, i * 2):
        s += i
    return s

In [ ]:
func(15)

In [ ]:
def bubble_sort(arr):
    n = len(arr)
    for elem in reversed(range(n)):
        for index in range(elem):
            if arr[index + 1] < arr[index]:
                arr[index], arr[index + 1] = arr[index + 1], arr[index]
    return arr

In [ ]:
sorted_arr = bubble_sort([1, 3, 2, 0, 4, 5, -1, 4])

In [ ]:
sorted_arr

In [ ]:
arr

In [ ]:
next(reversed(range(len(arr))))

In [ ]:
a = iter(reversed(range(len(arr))))

In [ ]:
print(*a)

In [ ]:
class Props:
    def __init__(self, x, y):
        self.x = x
        self.y = y

In [ ]:
class Ball(Props):
    def __init__(self, x, y):
        super().__init__(x, y)
        self.shape = "o"
        self.number = 1
        self.vely = 0
        self.velx = 0

    def get_x(self):
        return self.x

    def get_y(self):
        return self.y

    def get_velx(self):
        return self.velx

    def get_vely(self):
        return self.vely

    def inc_velx(self):
        self.velx = self.velx + 2

    def inc_vely(self):
        self.vely = self.vely + 1

In [ ]:
obj_ball = Ball(27, 3)

bx = obj_ball.get_x()
by = obj_ball.get_y()
b_velx = obj_ball.get_velx()
b_vely = obj_ball.get_vely()

print(bx, by, b_velx, b_vely)

In [ ]:
class A:

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):
        return 1

    def __eq__(self, other):
        return self.x * self.y == other.x * other.y


obj1 = A(9, 8)
obj2 = A(8, 9)
print(obj1 == obj2)

In [ ]:
T = int(input())

for i in range(T):
    A = input()
    count = 0
    for j in A:
        count += int(j) % 10
    print(count)

In [ ]:
num = int(input())
while num > 1:
    num = num // 3
print(num)

In [ ]:
89 // 3

In [ ]:
29 // 3

In [ ]:
9 // 3

In [ ]:
3 // 3

In [ ]:
check_prime(4)

In [ ]:
def check_prime(num):
    for j in range(2, num):
        if num % j == 0:
            return False
    return True

In [ ]:
sum_of_primes(11)

In [ ]:
class Student:
    def __init__(self, age):
        self.age = age

    def study(self):
        print("Study man")

In [ ]:
s1 = Student(1)

In [ ]:
s1.study()

In [ ]:
Student.__init__(s1, 2)

In [ ]:
s1.age

In [ ]:
s2 = Student(10)

In [ ]:
s2.age

In [ ]:
type(s1.study)

In [ ]:
class Car:
    wheel = 41
    door = 5

    def __init__(self, wheel, door):
        self.door = door

In [ ]:
maruti = Car(4, 5)

In [ ]:
tata = Car(4, 5)

In [ ]:
tata.wheel = 3

In [ ]:
tata.wheel

In [ ]:
maruti.wheel

In [ ]:
maruti.wheel = 4

In [ ]:
maruti.wheel

In [ ]:
tata.wheel

In [ ]:
Car.__dict__

In [ ]:
a = [2, 3, 4, 5]

In [ ]:
type(a[2:2])

In [ ]:
a[2:2] = 1

In [ ]:
a[2:3] = iter(range(3))

In [ ]:
a[2:3]

In [ ]:
a

In [ ]:
1 = 2

In [ ]:
class MYClass:
    def __init__(self, marks):
        self.marks = marks
        return

    def __str__(self):
        return "Hello"

    def __add__(self, other):
        return self.marks + other.marks

    def __lt__(self, other):
        return self.marks < other.marks

    def __gt__(self, other):
        return self.marks > other.marks

In [ ]:
p1 = MYClass(81)

In [ ]:
p2 = MYClass(91)

In [ ]:
p1 > p2

In [ ]:
type(p1.marks)

In [ ]:
p3 = MYClass

In [ ]:
p1 = p3(81)

In [ ]:
type(p1)

In [ ]:
print(p1)

In [ ]:
print(p2)

In [ ]:
"a".__str__()

In [ ]:
p1 + p1

In [ ]:
class Person:
    def say_hello(self):
        print("Hello")

In [ ]:
Person.say_hello("ajs")

In [ ]:
p1 = Person()

In [ ]:
p1.say_hello()

In [ ]:
class BankAccount:
    def __init__(self, balance):
        self.__balance = balance

    def deposit(self, amount):
        self.__balance += amount

    def withdraw(self, amount):
        if amount > self.__balance:
            print("Insufficient balance")
        else:
            self.__balance -= amount

    def check_balance(self):
        return self.__balance

In [ ]:
laks = BankAccount(100)

In [ ]:
laks.withdraw(50)

In [ ]:
laks.check_balance()

In [ ]:
laks.withdraw(50)

In [ ]:
laks.check_balance()

In [ ]:
laks.withdraw(10)

In [ ]:
laks.__dict__

In [ ]:
laks._BankAccount__balance = 1000

In [ ]:
laks.withdraw(250)

In [ ]:
laks.balance

In [ ]:
class SchoolMember:
    def __init__(self, name):
        self.name = name


class SchoolStudent(SchoolMember):
    def __init__(self, name, grade):
        super().__init__(name)
        self.grade = grade


class SchoolStaff(SchoolMember):
    def __init__(self, name, salary):
        super().__init__(name)
        self.__salary = salary

    def get_salary(self):
        return self.__salary


class SchoolTeacher(SchoolStaff):
    def __init__(self, name, salary, subject):
        super().__init__(name, salary)
        self.subject = subject
        self.__salary = salary


In [ ]:
s1 = SchoolTeacher('laks', 1000, 'maths')

In [ ]:
s1.get_salary()

In [ ]:
s2 = SchoolTeacher('uthra', 2000, 'science')

In [ ]:
s2.get_salary()

In [ ]:
class A:
    t = 8

    def __init__(self, x):
        self.x = x


class B:
    t = 10

    def __init__(self, y):
        self.y = y


class C(B, A):
    def __init__(self, x, y, z):
        A.__init__(self, x)
        B.__init__(self, y)
        self.z = z

In [ ]:
c = C(1, 2, 3)

In [ ]:
c.t

In [ ]:
c.y

In [ ]:
c.z

In [ ]:
class Car:
    def __init__(self):
        self.price = 100
        self.__cover = 5

    def display(self):
        print(self.__cover)


class Sedan(Car):
    def __init__(self):
        super().__init__()
        self.price = 200
        self.__cover = 10

In [ ]:
c1 = Sedan()

In [ ]:
isinstance(c1, Sedan)

In [ ]:
issubclass(__class_or_tuple, object)

In [ ]:
class Shape:
    pass


class Ellipse(Shape):
    pass


class Polygon(Shape):
    pass


class Circle(Ellipse):
    pass


class Rectangle(Polygon):
    pass


class Square(Rectangle):
    pass


class Triangle(Polygon):
    pass



In [ ]:
issubclass(Ellipse, Shape)

In [ ]:
issubclass(Circle, Shape)

In [ ]:
issubclass(Polygon, Ellipse)

In [ ]:
s = Shape()
e = Ellipse()
sq = Square()

In [ ]:
issubclass(e, s)

In [ ]:
isinstance(type, object)

In [ ]:
dir(object)

In [ ]:
type(int)

In [ ]:
type(function)

In [ ]:
Square.__mro__

In [ ]:
class A:
    x = 10


class B(A):
    pass


class C(B):
    pass


class D(A):
    x = 5


class E(D, C):
    pass

In [ ]:
e = E()

In [ ]:
e.x

In [ ]:
E.__mro__

In [ ]:
class A:
    x = 10


class B(A):
    pass


class E(B):
    pass


class F(B):
    pass


class G(F):
    pass


class H(G):
    pass


class I(G):
    pass


class J(H, I):
    pass


class K(J, E):
    pass


class C(A):
    pass


class C(D):
    pass


class L(C):
    pass


class M(J, L):
    pass


class N(M, D):
    pass


class O(K, N):
    pass

In [ ]:
O.__mro__

In [ ]:
func = lambda x: print(x) if x > 5 else 0

In [ ]:
func(21)

In [ ]:
students = [
    {"name": "A", "marks": 50},
    {"name": "B", "marks": 100},
    {"name": "C", "marks": 40},
    {"name": "D", "marks": 70},
    {"name": "E", "marks": 60}
]

In [ ]:
for i in range(len(students)):
    for key, value in students[i].items():
        print(key, value, end=' ')
    print()

In [ ]:
marks = lambda x: x["marks"]

In [ ]:
marks(students[3])

In [ ]:
students[0]["name"]

In [ ]:
students.sort()

In [ ]:
def mysrt(x):
    return x['name']

In [ ]:
students.sort(key=lambda x: x['marks'])

In [ ]:
students

In [13]:
def square(n):
    def pow(x):
        return x ** n

    return pow

In [ ]:
square(1024212)(4)

In [ ]:
def greet(name=input()):
    name = input()
    print(name)

In [ ]:
greet('laks')

In [7]:
def diff(A):
    n = len(A)
    xmin = float('inf')
    xmax = float('-inf')
    for i in range(n):
        if A[i] < xmin:
            xmin = A[i]
        if A[i] > xmax:
            xmax = A[i]
    return xmax - xmin

In [9]:
diff([3, 4, 5, 7787, 1010, 1901, ])

7784

In [10]:
map(lambda x: x ** 2, [1, 2, 3, 4])

In [14]:
list(map(square(x), [1, 2, 3, 4]))

NameError: name 'x' is not defined

In [23]:
def t_shirt_size(height):
    if height < 150:
        return "S"
    elif height >= 150 and height < 180:
        return "M"
    else:
        return "L"

In [24]:
t_shirt_size(175)

'M'

In [25]:
heights = [160, 165, 170, 175, 180, 185, 190, 120, 140, 135, 155]

In [26]:
list(map(t_shirt_size, heights))

['M', 'M', 'M', 'M', 'L', 'L', 'L', 'S', 'S', 'S', 'M']

In [29]:
list(map(lambda x: "S" if x < 150 else "M" if x >= 150 and x < 180 else "L", heights))

['M', 'M', 'M', 'M', 'L', 'L', 'L', 'S', 'S', 'S', 'M']

In [31]:
A = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
B = [1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0]

In [34]:
list(map(lambda x, y: x == y, A, B))

[True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True]

In [35]:
r1 = [1, 2, 3, 4, 5]
r2 = [6, 7, 8, 9, 10]
list(map(lambda x, y: x + y, r1, r2))

[7, 9, 11, 13, 15]

In [4]:
d = {['A', 'B', 'C', 'D']: i * 2 for i in range(10)}

TypeError: unhashable type: 'list'

In [3]:
d

{0: 0, 1: 2, 2: 4, 3: 6, 4: 8, 5: 10, 6: 12, 7: 14, 8: 16, 9: 18}

In [23]:
values = [x / (x - y)
          for x in range(10)
          if x > 5
          for y in range(10)
          if x - y != 0]

In [29]:
id('3')

1340932795824

In [37]:
a = 3019109890189981

In [39]:
a = 1

In [57]:
import sys

sys.getrefcount(b)

3416

In [58]:
r = [1, 2, 3]
s = r

In [59]:
id(r), id(s)

(1341034364992, 1341034364992)

In [60]:
s[0] = 7

In [61]:
r[0]

7

In [67]:
id(r[2]), id(s[2])

(1340930222448, 1340930222448)

In [68]:
p = [1, 2, 3]
q = [1, 2, 3]

In [69]:
id(p), id(q)

(1341034379328, 1341033317376)

In [70]:
p is q

False

In [71]:
p == q

True

In [72]:
p = 2
q = 2

In [73]:
p is q

True

In [74]:
p == q

True

In [75]:
p = [2]
q = [2]

In [76]:
p is q

False

In [79]:
p is p

True

In [89]:
f = [1, 2, 3]


def replace(g):
    g = [4, 5, 6]
    return g

In [90]:
h = replace(f)

In [91]:
id(h), id(f)

(1341033356864, 1341034669248)

In [88]:
h == f

True

In [93]:
h == f

False

In [116]:
s = map(func, [1, 2, 3])

In [117]:
list(s)

TypeError: func() missing 1 required positional argument: 'y'

In [115]:
def func(x, y):
    return x + 2

In [123]:
a = [1, 2, 3, 4]
b = ['l', 'u', 'v', {1, 2}]
list(zip(a, b))

[(1, 'l'), (2, 'u'), (3, 'v'), (4, {1, 2})]

In [126]:
from functools import reduce

In [128]:
a = [1, 2, 3, 4, 5]
reduce(lambda x, y: x + y, a)

15

In [130]:
a = [1, 2, 3, 4, 5]
reduce(lambda x, y: x * y, a)

120

In [131]:
a = list(range(1, 11))
b = list(reversed(a))

In [132]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [133]:
b

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [136]:
reduce(lambda x, y: x * y, a) == reduce(lambda x, y: x * y, b)

True

In [143]:
reduce(lambda x, y: x if x > y else y, a)

234

In [139]:
a = [78, -1, 98, 101, 234, 67, 77, 89, 32, 45, 12, 29, 71]

In [179]:
def sum1(x, y, *laks):
    result = x + y
    if laks:
        result += reduce(lambda x, y: x + y, laks)

    return result


In [180]:
sum1(5, 6, 12)

23

In [164]:
sum({7, 7, 8, 9})

24

In [207]:
def create_person(name, age, gender, **kwargs):
    Person = {
        "name": name,
        "age": age,
        "gender": gender,
    }
    if kwargs:
        Person.update(kwargs)
    return Person

In [218]:
p1 = create_person('laks', 46, gender="Male", hobby="jogging", habit='sleeping', working_at="EY")

In [219]:
p1

{'name': 'laks',
 'age': 46,
 'gender': 'Male',
 'hobby': 'jogging',
 'habit': 'sleeping',
 'working_at': 'EY'}

In [224]:
def random(x, y, *args, **kwargs):
    print(x)
    print(args)
    print(kwargs)

In [227]:
random(1, y=2)

1
()
{}


In [233]:
del len

NameError: name 'len' is not defined

In [234]:
len(a)

13

In [1]:
10 ** 0.5

3.1622776601683795

In [3]:
n = 125

In [5]:
n ** 2

15625

In [1]:
def check(n):
    return True if n > 0 else False

In [2]:
check(-3)

False

In [7]:
j = 4
for i in range(1, 100, j * 2):
    print(i)
    j = j * 2

1
9
17
25
33
41
49
57
65
73
81
89
97


In [52]:
def loop(N):
    count = 0
    j = 1
    for i in range(N):
        for j in range(1, N + 1, j * 2):
            count += 1
    print(count)

In [60]:
loop(80)

1640


In [56]:
import math

In [61]:
math.log(80)

4.382026634673881

In [89]:
def loop(N):
    count_i = 0
    count_j = 0
    for i in range(1, N + 1):
        for j in range(1, N + 1, i * 2):
            print(count_i, count_j)

In [90]:
loop(10)

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
2 0
2 1
3 0
3 1
4 0
5 0
6 0
7 0
8 0
9 0
10 1


In [11]:
def loop(N):
    count = 0
    j = i = 1
    while i < N + 1:
        j = 1
        while j < N + 1:
            count += 1
            j = j * 3
        i += 1
    print(count)

In [12]:
loop(1000)

7000


In [5]:
import re

In [27]:
email_pattern = "^\w+([\.-]?\w+)*@\w+([|.-]?\w+)*(\.\w{2,3})+$"
vemail = re.search(email_pattern, 'ajsjas@gmailszhdhs.co')

In [29]:
vemail

<re.Match object; span=(0, 21), match='ajsjas@gmailszhdhs.co'>

In [20]:
type(vemail)

NoneType

In [2]:
import numpy as np

In [36]:
a = np.array([1,2,3,4,5])

In [37]:
b = a[a>=2]

In [28]:
c = a[1:3]

In [29]:
np.shares_memory(a,c)

True

In [30]:
c

array([2, 3])

In [33]:
a[1] = 21

In [38]:
b

array([2, 3, 4, 5])

In [39]:
a.view()

array([1, 2, 3, 4, 5])

In [40]:
a

array([1, 2, 3, 4, 5])

In [44]:
a = np.array([1,2,[1,2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [10]:
class Stock:
    def __init__(self, ticker, price, company):
        self.ticker = ticker
        self.price = price
        self.company = company
    def get_description(self):
        return f"{self.ticker}: {self.company} -- ${self.price}"

In [16]:
msft = Stock("MSFT", 342.0, "Microsoft Corp")

In [17]:
print(msft.get_description())

MSFT: Microsoft Corp -- $342.0
