In [2]:
### Pattern Printing

In [4]:
# *****
# ****
# ***
# **
# *

In [1]:
import numpy as np

n = int(input())
for r in range(n):
    for c in range(n - r, 0, -1):
        print('*', end='')
    print()

ValueError: invalid literal for int() with base 10: ''

In [12]:
# *
# **
# ***
# ****
# *****

In [19]:
n = int(input())
for r in range(1, n + 1):
    for c in range(r):
        print('*', end='')
    print()

*
**
***
****
*****


In [20]:
# *
# *2
# *2*
# *2*4
# *2*4*
# *2*4*6

In [66]:
n = int(input())
for r in range(0, n):
    for c in range(r + 1):
        print(chr(ord('A') + c), end=' ')
        # if c % 2 != 0:
        #     print('*', end=' ')
        # else:
        #     print(c, end=' ')
    print()

A 
A B 
A B C 
A B C D 
A B C D E 


In [44]:
# *****
# ****
# ***
# **
# *

In [ ]:
n = int(input())
for r in range(n):
    for s in range(r):
        print('  ', end='')
    for c in range(n - r, 0, -1):
        print('* ', end='')
    print()

In [78]:
#     *
#    ***
#   *****
#  *******
# *********

In [96]:
n = int(input())
for r in range(n):
    for s in range(n - r):
        print(' ', end='')
    for c in range(2*r + 1):
        print('*', end='')
    for t in range(n - r):
        print(' ', end='')
    print()

     *     
    ***    
   *****   
  *******  
 ********* 


In [97]:
i = 1
while i % 7:
    for j in range(3):
        print("*")
    i += 1

*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*


In [101]:
nested_tup = ((4, 5, 6), (7, 8), [1,2])

In [106]:
nested_tup[2][0] = 3

In [107]:
nested_tup[2]

[3, 2]

In [113]:
s = {1,2,3}

In [134]:
a = [[1,2]]
b = [3,4]

In [135]:
c = a+a

In [136]:
id(c[0])==id(c[1])

True

In [137]:
c[0][0] = 100

In [138]:
c

[[100, 2], [100, 2]]

In [142]:
a = range(10)

In [152]:
from decimal import Decimal

l = [1,2,5,Decimal('2.5')]

In [153]:
min(l)

1

In [161]:
import numpy as np
data = np.array([[1,2,3],
                 [4,5,6]])
data2 = np.array([[1,2,3],
                 [4,5,6],
                 [4,5,6]])

In [165]:
data = np.array(range(10))

In [168]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [170]:
data.astype('float64')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [180]:
import pandas as pd
def relu(n):
    if n < 0:
        return 0
    return n

arr = pd.Series([1, 0, 1])
print(relu(arr.all()))

False


In [196]:
ls = [1,2,3,4,5,6]
ls_slice = ls[2:5]

In [197]:
ls_slice

[3, 4, 5]

In [198]:
ls_slice[:] = [11,12]

In [199]:
ls_slice

[11, 12]

In [200]:
ls = [[1,2,3], [4,5,6]]

In [203]:
import numpy as np

In [204]:
arr2d = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

In [219]:
tuple = arr2d[1,:2]

In [228]:
arr2d[:2,2]

array([3, 6])

In [2]:
import numpy as np

In [37]:
b = np.array([3,2,3])

In [38]:
b[[True, False, True]]

array([3, 3])

In [39]:
b[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [43]:
b[b<4]

array([3, 2, 3])

In [44]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])

In [49]:
A+1

array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6])

In [48]:
[x+1 for x in A]

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [51]:
list(map(lambda x: x+1, A))

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [52]:
A.shape

(10,)